################################### JAVA SETUP ######################################

language: java

jdk:
- oraclejdk8

sudo: false # faster builds

notifications:
  email: false
  
################################### GRADLE SETUP ######################################

env:
  global:
    - COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN
    
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
      
before_install:
 - chmod +x gradlew

################################ POST SUCCESSFUL BUILD ################################

######## RUN CODE COVERAGE ########

before_script:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - ./gradlew jacocoTestReport coveralls

################################## DEPLOYMENT STEPS ###################################

before_deploy:
  - test $TRAVIS_TEST_RESULT = 0
  - echo "tag detected as $TRAVIS_TAG"
  - ./gradlew assemble -PprodVersion=$TRAVIS_TAG
  - export RELEASE_DIR="build/libs"
  - export RELEASE_PKG_FILE=$RELEASE_DIR/FRC2017Robot-$TRAVIS_TAG.jar
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
  
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  skip_cleanup: true
  file: "$TRAVIS_BUILD_DIR/$RELEASE_PKG_FILE"
  on:
    tags: true    